### ISSUE TITLE
When do I have to manually post a photo? 

### ISSUE THREAD

**Issue by frankmeeuwsen** [aaronpk/OwnYourGram#54]
I posted a photo on Instagram this morning and it shows up in my dashboard on Ownyourgram. It has a Post button, but I want it to post automatically. That's what the service does right? Or do I have to manually go to the dashboard and post the photos myself?
And how would I know how long it will take for a photo to post automatically to my endpoint? How would I know about the possible errors?
I'm still learning...

Thanks!
Frank

**Comment by frankmeeuwsen** [comment]
This issue has been fixed by itself. My latest photo got posted about 16 hours later.

**Comment by aaronpk** [comment]
For the record, OwnYourGram is based around a tiered polling schedule in order to accommodate a variety of users. New users were starting out in tier 2 (checking every 6 hours). I updated OwnYourGram to start new users in the top tier, every 15 minutes, so that hopefully they'll have a better first experience.
