### ISSUE TITLE
Posts with multiple photos send as undocumented `photo[]` arg

### ISSUE THREAD

**Issue by jjdelc** [aaronpk/OwnYourGram#56]
The docs say that for multiple photos only one file will be sent:

> `photo` - The photo will be sent in a parameter named "photo". There will only be one photo per request. For Instagram videos, this will be the thumbnail of the video.

Still, in the dashboard there's an option to include all pics on multi photo post. But the payload actually includes all the photos under a `photo[]` arg, not `photo` (contrary to what the docs say). In some frameworks these two keys are actually different so the code needs to account for both possibilities. 

The micropub spec says that photos will be sent as `photo` argument, not `photo[]` https://www.w3.org/TR/micropub/#uploading-files

**Comment by aaronpk** [comment]
Thanks, I hadn't updated the docs since adding support for Instagram's multi-photos. 

Docs are updated now to reflect that: https://ownyourgram.com/docs

That "[uploading files](https://www.w3.org/TR/micropub/#uploading-files)" example is an example of uploading a single file. The syntax section above talks about the `photo[]` syntax: https://www.w3.org/TR/micropub/#form-encoded-and-multipart-requests I've updated the OwnYourGram docs to say that explicitly as well. Thanks for pointing this out!
