### ISSUE TITLE
Photos not showing (broken images)

### ISSUE THREAD

**Issue by adactio** [aaronpk/OwnYourGram#61]
OwnYourGram has stopped working for me. Well, technically it's still working because posts are being sent to my micropub endpoint, but images aren't coming through.

This isn't just at my end: when I look at https://ownyourgram.com/photos the most recent Instagram posts show broken images. If I copy the URL of the broken image source, I get https://ownyourgram.com/Array

The last post that worked was on February 8th. The breaking started (or was observed) around February 12th or so.

Here's a post that worked:
https://www.instagram.com/p/Be74gRrl_qF/
https://adactio.com/notes/13409

Here's one that didn't:
https://www.instagram.com/p/BfDRck0FHxK/

Is anyone else having issues?

**Comment by aaronpk** [comment]
aha, I definitely messed something up when I did some refactoring last week! When an account set to single-photo mode posts a multi-photo, it was failing in this way.

Speaking of which, since it seems you post several multi-photos on Instagram, you might want to consider supporting that on the Micropub side! From your dashboard, you can choose the multi-photo mode and OwnYourGram will upload all the photos to your endpoint. PHP will see `$_FILES['photo']` as an array in this case.

**Comment by adactio** [comment]
Thanks for fixing this, Aaron! The most recent photo came through loud and clear.

And yes, I definitely want to get multi-photo posting set up on my end. I stupidly architected my system to only ever expect one photo per post. Time for a bit of a refactor at the next Brighton Homebrew Website Club.
