### ISSUE TITLE
Manually importing a photo just results in spinning icon

### ISSUE THREAD

**Issue by vishae** [aaronpk/OwnYourGram#89]
I just tried to manually import a photo by entering the Instagram link directly.

It takes me to the Import a Photo page with the spinning arrow icon, but it just keeps spinning and nothing happens.

Also, the same page displays the Last Import Photos, and although the post text shows up, all the images are showing a broken link icon.

![Image 4-9-20 at 12 32 pm](https://user-images.githubusercontent.com/6110232/92193923-ced3e400-eeac-11ea-9f8f-3e0aef40d1ac.jpg)

**Comment by aaronpk** [comment]
Instagram has been cracking down on this kind of unofficial access to your photos. I'm afraid it's a bit of a cat and mouse game at this point, and I'm the mouse and the cat is winning. I'm not sure I have the energy to keep going with this since ultimately it means continuing to support Facebook. I'll leave this issue open until I decide whether to shut the whole thing down or try to keep going with it.

**Comment by vishae** [comment]
That's cools, I kind of expected that would be the case. I just wanted to make sure it wasn't me.

**Comment by aaronpk** [comment]
Closing this as Instagram has continued to crack down on things like this and it's not worth fighting anymore, sorry! Keep an eye out for the browser extension version of this project.
